version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: gocodeeval_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456 # 设置你的root密码
      MYSQL_DATABASE: gocodeeval_db
      MYSQL_USER: gocodeeval_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gocodeeval_network

  redis:
    image: redis:alpine
    container_name: gocodeeval_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gocodeeval_network

networks:
  gocodeeval_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
